CREATE DATABASE ChamaJussa;
GO

USE ChamaJussa;
GO

CREATE TABLE Usuario
(
    IdUsuario VARCHAR(40) PRIMARY KEY NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(256) NOT NULL,
    Senha VARCHAR(60) NOT NULL
);
GO

CREATE TABLE OrdemServico
(
    IdOrdemServico UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    TituloProblema VARCHAR(150) NOT NULL,
    Equipamento VARCHAR(150),
    Local VARCHAR(150) NOT NULL,
    Descricao VARCHAR(500) NOT NULL,
    Imagem VARCHAR(255),
    Status VARCHAR(30) NOT NULL DEFAULT 'Aberta',
    IdUsuario VARCHAR(40) FOREIGN KEY REFERENCES Usuario(IdUsuario)
);
GO

CREATE TABLE Notificacao
(
    IdNotificacao UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Mensagem VARCHAR(255) NOT NULL,
    Lida BIT NOT NULL DEFAULT 0,
    IdUsuario VARCHAR(40) FOREIGN KEY REFERENCES Usuario(IdUsuario),
    IdOrdemServico UNIQUEIDENTIFIER FOREIGN KEY REFERENCES OrdemServico(IdOrdemServico)
);
GO

DROP DATABASE ChamaJussa

SELECT * FROM Usuario

SELECT * FROM OrdemServico

SELECT * FROM Notificacao